#!/usr/bin/env bash
#  Process and PID file
touch /var/run/myscript.pid
while :
do
	  trap 'rm -r /var/run/myscript.pid | echo "I hate the kill command"' SIGTERM
	  trap 'echo "Y U no love me?!"' SIGINT
	  trap 'rm -r /var/run/myscript.pid' SIGQUIT
	  echo "To infinity and beyond"
	  sleep 2
  done
